export const ACTION_START_GENERAL = "ACTION_START_GENERAL";
export const ACTION_SUCCESS_GENERAL = "ACTION_SUCCESS_GENERAL";
export const ACTION_FAIL_GENERAL = "ACTION_FAIL_GENERAL";
export const INIT_GENERAL = "INIT_GENERAL";

export const INITIAL_PROFESSION = "INITIAL_PROFESSION";
export const GET_PROFESSION_BY_ID = "GET_PROFESSION_BY_ID";

export const INITIAL_CLASSROOM = "INITIAL_CLASSROOM ";
export const GET_CLASSROOM_BY_ID = "GET_CLASSROOM_BY_ID";
