export const ACTION_START_STUDENT = "ACTION_START_STUDENT";
export const ACTION_SUCCESS_STUDENT = "ACTION_SUCCESS_STUDENT";
export const ACTION_FAIL_STUDENT = "ACTION_FAIL_STUDENT";
export const INIT_STUDENT = "INIT_STUDENT";
export const CLEAR_TESTS_STUDENT = "CLEAR_TESTS_STUDENT";

export const GET_ALL_STUDENTS = "GET_ALL_STUDENTS";
export const GET_ALL_STUDENT_TESTS = "GET_ALL_STUDENT_TESTS";
export const GET_STUDENT_DETAILS = "GET_STUDENT_DETAILS";
