export const ACTION_START_TEST = "ACTION_START_TEST";
export const ACTION_SUCCESS_TEST = "ACTION_SUCCESS_TEST";
export const ACTION_FAIL_TEST = "ACTION_FAIL_TEST";
export const INIT_TEST = "INIT_TEST";
export const ACTION_FAIL_TIMER = "ACTION_FAIL_TIMER";

export const ADD_TEST_DETAILS = "ADD_TEST_DETAILS";

export const ADD_TEST = "ADD_TEST";
export const ADD_TEST_SUCCESS = "ADD_TEST_SUCCESS";
export const UPDATE_TEST = "UPDATE_TEST";
export const GET_TEST = "GET_TEST";
export const GET_ALL_TESTS = "GET_ALL_TESTS";
export const SET_TESTS = "SET_TESTS";
export const CLEAR_TEST = "CLEAR_TEST";
export const SET_TEST_QUESTION = "SET_TEST_QUESTION";
export const FINISH_TEST = "FINISH_TEST";

export const INITIAL_SEARCH_TEST = "INITIAL_SEARCH_TEST";

export const ADD_QUESTION = "ADD_QUESTION";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const UPDATE_VIEW_QUESTION = "UPDATE_VIEW_QUESTION";
export const ORDER_VIEW_QUESTION = "ORDER_VIEW_QUESTION";

export const INSERT_USER_ANSWER = "INSERT_USER_ANSWER";
