export const ACTION_START_TEACHER_CLASS = "ACTION_START_TEACHER_CLASS";
export const ACTION_SUCCESS_TEACHER_CLASS = "ACTION_SUCCESS_TEACHER_CLASS";
export const ACTION_FAIL = "ACTION_FAIL";
export const ACTION_INIT_ERROR = "ACTION_INIT_ERROR";
export const ACTION_RESET_ADMIN = "ACTION_RESET_ADMIN";

export const ADD_TEACHER_CLASS = "ADD_TEACHER_CLASS";
export const REMOVE_TEACHER_CLASS = "REMOVE_TEACHER_CLASS";
export const INTI_USER_CLASS = "INTI_USER_CLASS";

export const UPDATE_STUDENT_CLASS = "UPDATE_STUDENT_CLASS";
